Correction before session 2021
42-AI/bootcamp_machine-learning pull request #103
Opened 2021-11-02 23:38 UTC by madvid

* multiple typo and errors correction
* new exercises
* maths coherence in dimension
* more precision in docstrings
*  etc

2021-11-03 09:59 UTC, ppeigne reviewed
Great job! Few typos to remove and its perfect

2021-11-03 09:59 UTC, ppeigne commented on module05/ex00/ex00.md
> +## Intructions:
Instructions instead ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex00/ex00.md
> +>> v1 = Vector([[0.0], [1.0], [2.0], [3.0]])
Le modèle classique d'exemples ne prends pas de chevrons et ne fait pas appel à print pour présenter les résultats attendus (cf tous les autres exemples ci après)

Ex: 
```
# Column vector of dimensions n * 1
v1 = Vector([[0.0], [1.0], [2.0], [3.0]])
v2 = Vector([[2.0], [1.5], [2.25], [4.0]])
v1.dot(v2)
# Output
18
```

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +All methods take a `list` or a numpy.`ndarray` as parameter.
Numpy est interdite comme librairie sur cet exo, est-ce normal d'accepter les nd.array en input ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +* `mean(x)` : computes the mean of a given non-empty list or array `x`, using a for-loop. The method returns the mean as a float, otherwise None if `x` is an empty list or array, or a non expected ty
Numpy forbidden ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +* `median(x)` : computes the median, which is also the 50th percentile, of a given non-empty list or array `x` . The method returns the median as a float, otherwise None if `x` is an empty list or ar
Numpy forbidden ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +* `quartile(x)` : computes the 1st and 3rd quartiles, also called the 25th percentile and the 75th percentile, of a given non-empty list or array `x`. The method returns the quartiles as a list of 2
Numpy forbidden ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +* `percentile(x, percentile)` : computes the expected percentile of a given non-empty list or array `x`. The method returns the percentile as a float, otherwise None if `x` is an empty list or array
Numpy forbidden ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +* `var(x)` : computes the variance of a given non-empty list or array `x`. The method returns the variance as a float, otherwise None if `x` is an empty list or array or a non expected type object. T
Numpy forbidden ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex02/ex02.md
> +* `std(x)` : computes the standard deviation of a given non-empty list or array `x`. The method returns the standard deviation as a float, otherwise None if `x` is an empty list or array or a non exp
Numpy forbidden ?

2021-11-03 09:59 UTC, ppeigne commented on module05/ex03/ex03.md
> +    Return:
Should be returns instead (3rd pers.), same as RaiseS below.

2021-11-03 09:59 UTC, ppeigne commented on module06/ex03/ex03.md
> +- $x$ is a vector of dimension $m * 1$,
use "\times" instead of "*" ?

2021-11-03 09:59 UTC, ppeigne commented on module08/ex12/ex12.md
> +Manipulation oof confusion matrix concept.
of

2021-11-03 10:01 UTC, ppeigne commented on module06/ex03/ex03.md
> +- $x$ is a vector of dimension $m * 1$,
Actually should be just dimension $m$

2021-11-03 10:40 UTC, ppeigne submitted a review, later dismissed
All good :)

2021-11-03 13:35 UTC, madvid commented on module05/ex00/ex00.md
> +>> v1 = Vector([[0.0], [1.0], [2.0], [3.0]])
J'ai pas compris, j'ai oublié de retirer des chevrons ?

2021-11-04 06:03 UTC, qfeuilla requested changes

2021-11-04 06:05 UTC, qfeuilla commented on module08/ex03/ex03.md
> +* $e$ is the contracted form for exponential function. It is also a mathematical constant, named Euler's number.
forget it, contracted is right

2021-11-04 08:24 UTC, ppeigne commented on module05/ex00/ex00.md
> +* `dot()`: produce a dot product with the vector given as parameter (should have the of same shape),
I sugest: "(both vectors should have the same shape)"

2021-11-04 08:35 UTC, ppeigne commented on module07/ex12/ex12.md
> +1. From a purely intuitive point of view, which hypothesis (i.e. which polynomial degree) seems to **better represent the relationship** between $y$ and $x$?
Point of view is OK in english (standpoint is a synonym).

2021-11-04 08:45 UTC, ppeigne commented on module09/ex00/ex00.md
> +You may have to take a look at Scikit-Learn's implementation of logistic regression and noticed that the `sklearn.linear_model.LogisticRegression` class offers a lot of options.
If you had taken a look at ... you should have noticed that ?

2021-11-05 14:28 UTC, madvid commented on module08/ex12/ex12.md
> +**N.B:** If you fail this exercise on your first attempt, Norminet will curse you forever. Yeah, you'd better do it right or you are in trouble my friend, big trouble!
For the moment, it is not important

2021-11-06 17:31 UTC, closed without merging