Merge on master
42-AI/bootcamp_machine-learning pull request #94
Opened 2020-12-08 07:36 UTC by ppeigne

Time to merge on master !!

2020-12-08 12:23 UTC, matboivin approved these changes

2020-12-08 18:03 UTC, llenotre commented on day03/ex03/ex03_interlude1.md
> +The good news is that we can keep the linear equation we already worked with! All we need to do is sqash its output through another function that is bounded between 0 and 1. That's the **Sigmoid func
Typo: "sqash" should be "squash"

2020-12-08 18:06 UTC, llenotre commented on day03/ex11/ex11_interlude.md
> +    - Considering that someone is not sick when she isn't.
Failure on negation: "isn't" should be "is"

2020-12-08 18:08 UTC, llenotre commented on day03/ex11/ex11_interlude.md
> +    - Considering that someone is not sick when she isn't.
Failure on negation: "isn't" should be "is"

2020-12-08 18:13 UTC, llenotre approved these changes
Found some typos

2020-12-08 20:51 UTC, madvid requested changes
principalement de l'homogeneisation dans les snippets de code, erreurs ponctuels de markdown (pb avec la generation d'une liste en raison d'espace devant le tiret ...)

2020-12-08 20:51 UTC, madvid commented on day00/ex00/ex00.md
>  - Multiplication and division between one vector (m * 1) and one scalar (1 * 1)
Pas besoin de préciser qu'un scalaire c'est (1*1)

2020-12-08 20:51 UTC, madvid commented on day00/ex00/ex00.md
> +print(v2)
cohérence dans les snippets de code: certaine ligne de code commence par ''>>'' et d'autre non (et les autres dont je parle ne sont pas les output des fonctions style print)

La référence de cette remarque sera désigné par **ID1**

2020-12-08 20:51 UTC, madvid commented on day00/ex00/ex00.md
> +```
absence de **ID1**

2020-12-08 20:51 UTC, madvid commented on day00/ex00/ex00.md
> +```
absence de **ID1**

2020-12-08 20:51 UTC, madvid commented on day00/ex01/ex01.md
> +#(Matrix [[28., 34.], [56., 68.]])
**ID1** partiellement present

2020-12-08 20:51 UTC, madvid commented on day00/ex01/ex01.md
> +```
absence de **ID1**

2020-12-08 20:51 UTC, madvid commented on day00/ex08/ex08.md
>  cost_(X, X)
**ID1** absent, commentaire s'applique aussi aux lignes avant et apres

2020-12-08 20:51 UTC, madvid commented on day00/ex11/ex11.md
>  ## sklearn implementation
**ID1** absent, regarder aussi les lignes avant et apres

2020-12-08 20:51 UTC, madvid commented on day00/ex12/ex12.md
>  ```
**ID1**

2020-12-08 20:51 UTC, madvid commented on day01/ex00/ex00.md
**ID1**

2020-12-08 20:51 UTC, madvid commented on day01/ex01/ex01.md
>  cost_(X, X)
**ID1**

2020-12-08 20:51 UTC, madvid commented on day01/ex10/ex10.md
>      """Computes the normalized version of a non-empty numpy.ndarray using the min-max standardization.
**ID1** dans le snippet d'apres dans la sous section exemple

2020-12-08 20:51 UTC, madvid commented on day00/ex01/ex01.md
>  - Multiplication or division between one matrix (m * n) and one scalar (1 * 1)
(1*1) pas necessaire pour le scalaire

2020-12-08 20:51 UTC, madvid commented on day00/ex02/ex02.md
>  >>> a = [1, 42, 300, 10, 59]
- [ ] **ID1** ici trop de chevron par rapport aux autres cas ou il y en a

2020-12-08 20:51 UTC, madvid commented on day00/ex03/ex03.md
**ID1** (s'applique a tout le snippet)

2020-12-08 20:51 UTC, madvid commented on day00/ex03/ex03_interlude1.md
> +\text{given } \theta = \begin{bmatrix}33 \\ 5 \end{bmatrix} \text{ and } x = \begin{bmatrix}1 \\ 3 \end{bmatrix} \text{: }
faudra voir à la generation si l'espace dans text{given } n'est pas tronqué, si c'est le cas on pourras rajouter un \smallskip ou \hspace{0.5cm}

2020-12-08 20:51 UTC, madvid commented on day03/ex10/ex10.md
> +    - The Asteroids' Belt colonies (3).
Probleme ici, la liste ne se fait pas en markdown /!\. Comme c'etait avant c'etati bon

2020-12-08 20:51 UTC, madvid commented on day03/ex10/ex10.md
> +    - $0$ if the citizen has another zipcode
indentation de niveau 2 sans etre passé par le niveau 1, c'est voulu ?

2020-12-08 20:51 UTC, madvid approved these changes

2020-12-09 05:14 UTC, ppeigne commented on day00/ex00/ex00.md
> +* `values` : list of lists of floats
C'est ça je pense !

2020-12-09 07:33 UTC, fxbabin approved these changes
LGTM

2020-12-09 07:42 UTC, madvid reviewed
une petite coquille dans un exemple et tout est parfait :partying_face:

2020-12-09 07:42 UTC, madvid commented on day00/ex00/ex00.md
> -# (Vector [0.0, 5.0, 10.0, 15.0])
transformer ```v2 = v1 * 5``` en ```v1 * 5 ``` de sorte a ne pas avoir besoin effectivement de ```print(v2)```

2020-12-09 07:45 UTC, madvid approved these changes

2020-12-09 08:00 UTC, ppeigne commented on day00/ex00/ex00.md
> -# (Vector [0.0, 5.0, 10.0, 15.0])
ARG

2020-12-09 11:28 UTC, llenotre approved these changes

2020-12-09 13:50 UTC, matboivin approved these changes

2020-12-09 13:51 UTC, matboivin commented
:tada:

2020-12-09 15:09 UTC, merged